#-------------------------------
# General Site Settings

title: Ashwin Vaidya
description: Computer Engineer, Space Buff # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Ashwin Vaidya
author-avatar: profile.jpg


#-------------------------------
# Contact links
# facebook:  # Add your Facebook handle
twitter:   https://twitter.com/ashwinvaidya17 # Add your Facebook handle
instagram: https://www.instagram.com/ashwin.vaidya17/ # Add your Facebook handle
#pinterest: https://www.pinterest.com/ # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: ashwinvaidya # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: UA-123420588-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp:

#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
